Legend-of-Dragoon-Modding/Severed-Chains

- src/main/java/legend/game/SStrm.java
- src/main/java/legend/game/Scus94491BpeSegment_8003.java
Makes a lot of the CDROM code interact directly with the CDROM emulator instead of communicating via registers. It's faster and fixes desyncs during concurrency. This should fix the fairly common crash on startup.
> [#15] Use direct CDROM methods (closes #15)

- src/main/java/legend/game/inventory/screens/SaveListScreen.java
> fix: only load as many saves as are available on continue

- src/main/java/legend/game/modding/events/EventManager.java
Since the EventManager walks like a duck for the Singleton pattern with the .INSTANCE property, it may be appropriate to modify the constructor to prevent initializations of the EventManager. Don't see any indicators that the EventManager will break the Singleton pattern with future expansion.
> Adhering EventManager to thread-safe Singleton model

- src/main/java/legend/game/SItem.java
The PR uses stats.hp_04 instead in menu displays. stats.hp_04 is more accurate than gamestate's hp_08 for menus.
hp_08 shouldn't be used in the menu display of HP as this does not sync with external sources of information (.dsavs, mods) on initial load of the game or when fresh events are consumed between battles. Stale values will thus be shown in the menu in these situations.
Since gamestate's hp_08 syncs with hp_04 before battle begins, this should be inconsequential. However, new to the codebase so may have overlooked a sync context with this somewhere!
Note 1: If I'm not incorrect, then gamestate's hp_08 should be refactored to be used only in battle to avoid future sync issues with future mod expansion (mods can target gamestate HP or out of combat HP events specifically).
Examples: …
> Fix HP in menus being out of sync from save files, mods

- src/main/java/legend/game/SItem.java
- src/main/java/legend/game/Scus94491BpeSegment.java
- src/main/java/legend/game/Scus94491BpeSegment_8004.java
- src/main/java/legend/game/combat/Bttl_800c.java
- src/main/java/legend/game/combat/Bttl_800e.java
- src/main/java/legend/game/combat/SBtld.java
- src/main/java/legend/game/combat/SEffe.java
- src/main/java/legend/game/combat/types/BattlePreloadedEntities.java
- src/main/java/legend/game/combat/types/BattlePreloadedEntities_18cb0.java
- src/main/java/legend/game/modding/events/characters/AdditionHitEvent.java
Deduced the classes pertaining to battle preloading and initialization and provided them with related names.
Refactored battleMapSelectedAdditionHitProperties to be more readable and extensible for future edits.
Tried to stay inline with the current naming schemes present.
BattlePreloadedEntities was the best name I could come up with for this class. We have a lot of miscellaneous collections of data present. From testing, it seems everything in this grouping is preloaded before the battle screen updates. Which is inline with the parent callers both initializing the battle and also beginning to load (see preload) assets and scripts. Thus, the name is implying that this is a collection of entities that can and must be preloaded before the battle screen updates. For this, it seems like an …
> Rename and refactor entities relating to battle preloading entities with a focus on additions

- src/main/java/legend/game/inventory/screens/ItemListScreen.java
- src/main/java/legend/game/inventory/screens/ShopScreen.java
• Refactored render code to be simpler with sharing one highlighter, one selectSlot
• Refactored vertical input handling to be as straightforward as a shared state dual pane distinct menu system can be
• Added logic that was missing to the Left and Right toggles of state 
• This may have conflicts with #268 (which did not address this bug)
• Equipment broke out of the boundaries on the Sell => Equipment/Items menu
• Armed is the original name and Armed is used elsewhere in the Menu system
• I did not restore the original menu in the mid left of the screen but kept the one already present
• See following screenshots for details
> List Menu Dual Highlight Bug Fix + Shop Screen Sell DRG Alignment Fix

- src/main/java/legend/game/combat/Bttl_800f.java
- src/main/java/legend/game/combat/types/BattleObject27c.java
The condition for checking against status chance was dividing the random seed value by 0x100 instead of shifting right 0x10, so the values being compared to the status chance were too high by a factor of 0x100.
Also corrected an annotation.
> Status chance fix

- src/main/java/legend/game/combat/Bttl_800f.java
As discussed in discord, it seems that some offsets used were incorrect, causing wrong values to be read from the bobj. Changes are based off these addresses in the ghidra decomp, where the index is the attack type and 0x800c73c is the base address:
```
local_68[0] = DAT_BTTL__800c703c;
local_68[1] = DAT_BTTL__800c7040;
local_68[2] = DAT_BTTL__800c7044;
local_58[0] = DAT_BTTL__800c7048;
local_58[1] = DAT_BTTL__800c704c;
local_58[2] = DAT_BTTL__800c7050;
local_48[0] = DAT_BTTL__800c7054;
local_48[1] = DAT_BTTL__800c7058;
local_48[2] = DAT_BTTL__800c705c;
local_38[0] = DAT_BTTL__800c7060;
local_38[1] = DAT_BTTL__800c7064;
local_38[2] = DAT_BTTL__800c7068;
```
> Fix healing items missing occasionally bug

- src/main/java/legend/core/Config.java
- src/main/java/legend/game/combat/Bttl_800f.java
- src/main/java/legend/game/debugger/DebuggerController.java
- src/main/resources/legend/game/debugger/debugger.fxml
Adds option to disable status effects to debugger. Only applies to the party.
The logic is supposed to be that if the option is enabled, the status effect code should still be entered if the "attacker" is the player, but that if the attacker is an enemy it will always be skipped.
Closes #312
> Disable status effects

- src/main/java/legend/game/combat/SEffe.java
- src/main/java/legend/game/combat/types/BattleStructEF4/AdditionExtra04.java
As discussed in Discord voice chat, tracked down the script flag set by equipping Ultimate Wargod and altered it to set when the debug option is checked. Fortunately, this script is called when attacking and not just at combat startup, so it is still possible to turn this on/off in the middle of battle. Equipped accessory properties appear to be unaffected so far (have tried Spirit Ring, Wargod Sash, and Physical Ring, as they have varied effect types).
> Auto addition fixed

- src/main/java/legend/game/Scus94491BpeSegment_8002.java
Retail seems to sort by icon and then by item id. 
Tested against Emulator and PS1 sorting...seems to match up but hard to get 1:1 comparisons for all items.
Commit history has sub-sorting alphabetically for future reference. #options #mods
Closes #220 
*No idea the CS for the chained comparator delegates.*
> Retail Accurate item and equipment sorting

- src/main/java/legend/game/inventory/screens/MainMenuScreen.java
Added the functionality to wrap and massively reduced the nesting / code complexity for the functionality to exist (see commit history).
In retail the only menu I found that does wrap is the main menu. The other menus don't seem to wrap.
Closes #296
> Main menu selector wraps / loops

- src/main/java/legend/game/scripting/ScriptManager.java
Allocator was not setting enough storage indices to -1. We hope.
> Fixes #174, breaks ???

- src/main/java/legend/game/combat/Bttl_800f.java
A deref got missed in reversing, so offset _d6 was being accessed in the attacker state instead of the attacker bobj, which is where itemElement is stored.
Also did some renaming and minor cleanup.
> Fixes #347

- src/main/java/legend/game/combat/Bttl_800f.java
- src/main/java/legend/game/combat/types/BattleObject27c.java
It turns out that scripted mass status effect attacks like Menon's confusion or DD's roar do not use the same code for determining and applying effects. To get it to work universally, I added checks to the bobj getStat function. Now, any time something tries to get status_0e or statusResistFlag_24, it will check whether disableStatusEffects is on and charSlot is >0 (which to my knowledge is player characters only). If it is, the character will be set to resist all statuses, and current conditions will be cured. This should catch all status effects, but things like arm blocking could use some testing in terms of whether this fix will remove it if already applied (something the old method didn't do at all).
> disableStatusEffect fix

- src/main/java/legend/game/combat/Bttl_800c.java
The script engine was checking a value on storage[7] of the bobj scripts prior to animation loading, but the flag was only being set on Dart. Turns out a single memory value set to 0 was being used to index the bobj scripts instead of the loop value.
> Victory dance fixed

- src/main/java/legend/game/combat/Bttl_800e.java
- src/main/java/legend/game/combat/SEffe.java
textureInfo RECTs in the DEFF were being indexed incorrectly, and a VRAM copy call had a wrong argument.
There are still issues with the transformation (effects playing when they shouldn't), but I think that these are likely a different type of issue that may be connected to other spells having effects displaying when they shouldn't.
> Fix Dart Red-Eye Transformation (closes #390)

- src/main/java/legend/game/SMap.java
- src/main/java/legend/game/Scus94491BpeSegment_8002.java
- src/main/java/legend/game/WMap.java
- src/main/java/legend/game/combat/Bttl_800d.java
- src/main/java/legend/game/combat/Bttl_800e.java
- src/main/java/legend/game/combat/SEffe.java
- src/main/java/legend/game/tmd/Renderer.java
This PR mainly fixes issues in the universal renderer where certain effects need to have uniform lighting applied, which was originally done in the CTMD renderers when certain flags were set (CTMD primitive flag and `dobj.attribute_00 == 0x4000_0000`).
Aside from that, I also fixed a small flag issue in allocateDeffTmd (a line was supposed to be `= 0x300_0000`, not `|= 0x300_0000`, see 80118554 in ghidra), and changed how 80113ba0 was ordered to match 801146fc, which appears to be an equivalent function for a different transformation metric. These changes are related to some of the fixed effects (like mouse's bite) as well, dealing with the transformation of these deff effects.
> Rendering fixes

- src/main/java/legend/game/combat/Bttl_800e.java
Just a small change to a variable name, to be more easy to identify the origin-meaning of the value
> Changing a variable name - Bttl_800e.java

- src/main/java/legend/core/Config.java
- src/main/java/legend/game/Scus94491BpeSegment.java
- src/main/java/legend/game/debugger/DebuggerController.java
- src/main/resources/legend/game/debugger/debugger.fxml
Adds a game speed multiplier to the debugger and to direct keyboard support with - and = keys.
The keyboard controls both require checks in the .onKeyPress and .onKeyRepeat in the GPU gameLoop() to receive nice behaviour with the - and = inputs. Not sure what other way to do this is better.
Think we should limit this to debug-focused purpose first before implementing it in the config option being saved in save files, if applicable. Iron out use-cases and/or bugs. Other considerations like game play integrity of saves is a discussion.
Is this going on on main?
Initial loading screen effects are slowed down inversely to the multiplier (fade in, fade out). The menu or game is still fully playable...you just may not be able to see anything for 1-3 seconds.
VSync settings are hardcoded in …
> Game Speed Multiplier

- src/main/java/legend/game/tmd/Renderer.java
After looking through all of the CTMD renderers and all the STMD renderers for SMAP, BTTL, and WMAP, it appears that all TMD rendering should use back-face culling. I moved the winding and culling code out from the useSpecialTransparency check, which does not appear to be relevant to control culling, other than possibly secondarily through transparency. 
Fixed by this PR:
- #289 
- #308 
- #355 
- Normals on Albert's hands when receiving JDS
- Certain crates not rendering properly
- Probably a bunch of other stuff we haven't catalogued
> Back-face culling now always used when rendering TMDs

- src/main/java/legend/game/Scus94491BpeSegment_8004.java
- src/main/java/legend/game/combat/Bttl_800d.java
- src/main/java/legend/game/combat/SEffe.java
This fixes the parabolic arc for thrown items (SEffe L6877) and fixes rotation issues for several spells (Spectral Flash, Dancing Light, Psyche Bomb at minimum) as well (Bttl_800d L4913 and SEffe L7660-7665).
Would like some feedback/suggestions on xxxTranslationScalerWithRotation name scheme, as well as some name suggestions for 8011299c, 80111ed4, 80110120,  and 80110228 (and unnamed variables inside them).
> Fixed several rotation-related bugs

- src/main/java/legend/game/combat/SEffe.java
When initializing the structs at the start of the addition, the pointer was being decremented one time too many at the end of the loop. Moved the decrement to the start of the loop and removed the standalone decrement before the loop.
There was another bug at L3732-3734, where the subtraction is supposed to be performed prior to division. This definitely changes some values, but I can't tell what the effect is in-game.
Closes #414
> Fixed targeting squares not being correct

- src/main/java/legend/game/combat/SEffe.java
When constructing the gp0 packet in retail, the u value is right-shifted by 6 to fit it into the low nibble of the tpage in the packet, so the lowest 6 bytes are removed when multiplying by 64 to calculate VRAM position. u is composed of VRAM X + u, so in SC, the u needed to be factored out as well.
Fixes Melbu's solar system attack and ??? other effects.
> Fixes sprite renderer called by processLmb methods

- src/main/java/legend/game/combat/Bttl_800d.java
Someone tried to slide some XXX content into LoD.
Fixes #477
> Fixes the loopy camera during Fruegel's smash attack

- src/main/java/legend/game/combat/Bttl_800e.java
The energy blast effects were still being rendered very close to the camera, causing pixel coordinates to overflow.
> Fix #466 (Lloyd crash)

- src/main/java/legend/game/combat/Bttl_800e.java
Turns out the original check is needed as well to keep the tentacles from crashing in combat.
> Add back z >= 0x28

- src/main/java/legend/game/Scus94491BpeSegment.java
MCQs use gp0 command 7c, which does not have transparency.
> Removes transparency command from MCQs

- src/main/java/legend/game/combat/SEffe.java
a2._50 is an SVEC, not a VEC, so param 2 + 54 in ghidra equates to the Z value rather than the Y value.
> Fixes heal particle movement

- src/main/java/legend/game/tmd/Renderer.java
TMD normals were not being used for vertices that exceeded the number of normals (so quads from objects with 3 or fewer normals or triangles from objects with 2 or fewer). Corrected so that the normal index of a vertex is compared against the number of normals. This probably fixes a several things, but most noticeably it fixes Albert's cape.
> Fixes issues with some normals

- src/main/java/legend/game/SItem.java
- src/main/java/legend/game/SMap.java
- src/main/java/legend/game/combat/Bttl_800c.java
- src/main/java/legend/game/combat/Bttl_800e.java
- src/main/java/legend/game/unpacker/FileData.java
- src/main/java/legend/game/unpacker/MrgArchive.java
- src/main/java/legend/game/unpacker/Unpacker.java
It turns out that sometimes virtual files with sizes are referenced by indices hardcoded into scripts, and not having them present causes a softlock when the animation cannot be found (as with Lenus' water attacks and the floating animation). I double-checked the retail code in ghidra, and all the places we do `real()` checks, retail is just checking for `size != 0`, regardless of whether the file is a duplicate. To match that, I added a virtualSize to FileData that always holds the size found in the MRG table, and `real()` now checks that this isn't zero.
Fixes #558
> Adds virtualSize to FileData

- src/main/java/legend/core/gpu/Gpu.java
Explanation is here: https://discord.com/channels/307164262063669248/318595603636551701/1112237383312748564
Relevant no$ documentation:
```
GP0(E6h) - Mask Bit Setting
0     Set mask while drawing (0=TextureBit15, 1=ForceBit15=1)   ;GPUSTAT.11
1     Check mask before draw (0=Draw Always, 1=Draw if Bit15=0) ;GPUSTAT.12
2-23  Not used (zero)
24-31 Command  (E6h)
When bit0 is off, the upper bit of the data written to the framebuffer is equal
to bit15 of the texture color (ie. it is set for colors that are marked as
"semi-transparent") (for untextured polygons, bit15 is set to zero).
```
Double check me, but I think this is the correct fix to use. I see no documentation for any instance where the transparency bit is forced to 0, so it should always be 1 (forced) or whatever is set in the …
> Uses texel's transparency bit when bit15=1 not forced

- src/main/java/legend/game/Scus94491BpeSegment_8004.java
- src/main/java/legend/game/combat/Bttl_800c.java
- src/main/java/legend/game/combat/Bttl_800d.java
- src/main/java/legend/game/combat/effects/RadialGradientEffect14.java
`effect._01` is supposed to be set using an unsigned comparison, not signed (L768).
> Fixes potion ring/Detonating Arrow effects

- src/main/java/legend/game/combat/SEffe.java
Particle position was being set to a position difference vector twice instead of having the difference vector subtracted from it.
> Fixes wounded Virage claw attack dust

- src/main/java/legend/game/combat/Bttl_800e.java
- src/main/java/legend/game/combat/SEffe.java
- src/main/java/legend/game/combat/deff/DeffManager7cc.java
- src/main/java/legend/game/combat/deff/DeffPart.java
Some vertex difference animations use multiple copies of the same file within a DEFF. In retail, all of the deff parts are copied into memory, and all TMDs (and other types) are set as references to these parts, rather than new copies. That means that if multiple scripts reference the same part, any changes made to the TMD in one script are also reflected in the other scripts. Therefore, any vertex difference calculations can be performed once on a single script, and the change will be reflected across all scripts referencing that part, each of which can have its own translation, rotation, etc.
The issue in SC was that every time a new DEFF TMD was allocated, getDeffParts would return a new copy of the TMD data to attach to the script state. Thus, transformations performed on a script …
> Change how DEFF files are referenced when package is loaded

- src/main/java/legend/game/Scus94491BpeSegment_8004.java
- src/main/java/legend/game/combat/Bttl_800c.java
- src/main/java/legend/game/combat/effects/WeaponTrailEffect3c.java
- src/main/java/legend/game/combat/effects/WeaponTrailEffectSegment2c.java
The crash itself was being caused by some mixups between the various smallest/largest vertex attributes. This *should* be correct now, and the trails I've compared seem to match.
Also added a coordinate size threshold to the trail rendering method that will prevent a trail from rendering if it has any very large coordinates. This prevents for instance garbage trail pieces in Kanzas' attack from rendering across the screen. These segements are rendered in retail, but for whatever reason they do not end up visible in the final raster. This hack is to imitate that.
> Fixes Kanzas' daddy issues

- src/main/java/legend/core/gpu/Gpu.java
- src/main/java/legend/core/gpu/VramTextureSingle.java
Prevents texels from turning negative when large coords are interpolated by using longs instead of ints.
Fixes #622
> Interpolate using longs

- src/main/java/legend/game/inventory/screens/MainMenuScreen.java
Currently if you click character portraits, or anything but the main menu buttons you will lose focus to a non-button control. Then the current code doesn't know how to process the index in the button delegates for controller/kb inputs.
This change checks to make sure the main menu focus is retained to the main menu buttons only, even if the mouse clicks outside of it.
Not sure if this is the best place to make this change but it doesn't impact the other screens so it seems unique to mainmenuscreen.java.
> Fix mouse clicks destroying conroller/kb controls on main menu

- src/main/java/legend/game/inventory/screens/MessageBoxScreen.java
• state_0c ==5 and state=_0c == 4 seem to only be used during message box fade out animations
• Since this is the intent of the two states, it seems appropriate to use them
• skipInput is the logical choice to place this check
• This avoids the messageBox from detecting and reacting to any input during the animation
• If someone has used state 5 or state 4 for something weird...that should be fixed when found
• This will help prevent people using the awkward message box handlers and overrides incorrectly by doing them a favour and locking them out of state 5 and state 4 input concerns lol ✔
• The initial animation of the message box growing in size is not cancelled and the fullsize message box animation is where it begins, so it looks slightly choppy if you know to watch for it
• Tested …
> Fix messageBox fade out spam

- src/main/java/legend/game/combat/Bttl_800f.java
- src/main/java/legend/game/types/SpellStats0c.java
Prior to stats changes, the fields grouped into SpellStats0c were set to 0 when spellID was >127. This got changed to setting bobj.spell_94 to null, which throws an error when the checkHit method tries to access one of the values. Thought about adding a null check, but thought replicating the prior behavior with a default constructor would be safer.
> Fixes crash when using weapons that apply poison

- src/main/java/legend/game/Scus94491BpeSegment_8004.java
- src/main/java/legend/game/combat/Bttl_800d.java
- src/main/java/legend/game/combat/Bttl_800e.java
- src/main/java/legend/game/combat/SEffe.java
- src/main/java/legend/game/combat/effects/BillboardSpriteEffect0c.java
- src/main/java/legend/game/combat/effects/SpriteWithTrailEffect30.java
- src/main/java/legend/game/combat/effects/TmdSpriteEffect10.java
Renamed AttackHitFlashEffect0c to BillboardSpriteEffect0c, named a bunch of stuff related to sprite methods, and fixed bug where the circumscription in Gravity Grabber was messed up. The issue was that a copy of the transform matrix was made and used, when the original matrix actually needed to be modified (see variable local_c4 in ghidra). This should affect all of the sprite with trail effects, although whether that's noticeable depends on the effects themselves.
> Gravity rubber fix

- src/main/java/legend/game/submap/SMap.java
When Dart is facing exactly in a cardinal direction, moving exactly the opposite direction would leave one of the deltas at 0, which would skip the y rotation recalculation. Originally there was no check for this. I changed it so as long as one delta is non-zero, it would recalculate the y rotation, so it will still do nothing in the case where both deltas are zero.
Fixes #748 (commit 89a55bd5 was where the bug was introduced)
> Fix Dart moonwalking

- src/main/java/legend/game/wmap/WMap.java
`colour_8c` still has to use `COLOUR`, so values need to be converted between float and byte to prevent the setting of `colour_8c` from exploding.
> Fixed WMAP lighting crash

- src/main/java/legend/game/wmap/WMap.java
- src/main/java/legend/game/wmap/WmapSmokeInstance60.java
The smoke clouds are behaving correctly now. I *think* the changes are placed correctly according to the asm. The initial struct pointer is set just before the first loop, and the pointer is advanced to the next struct in the array right after the GPU packet is queued inside the inner loop. It seems to be done this way because any single location only has 6 smoke cloud instances, but you can have multiple locations with smoke clouds in a continent at the same time, which is why the pointer increments separately from both the inner and outer loops.
> Fixed another wmap smoke bug

- src/main/java/legend/game/wmap/WMap.java
- src/main/java/legend/game/wmap/WMapStruct19c0.java
- src/main/java/legend/game/wmap/WMapStruct258.java
- src/main/java/legend/game/wmap/WmapStateEnum.java
Old L6808 was the reversed condition preventing rendering. There was also an incorrect color change at old L6732 (-0x20, not -0x2).
Also condensed the conditions in the renderer a bit to reduce nesting. Named some fields while I was at it.
> Wmap cloud fix

- src/main/java/legend/game/wmap/WMap.java
- src/main/java/legend/game/wmap/WMapAtmosphericEffectInstance60.java
- src/main/java/legend/game/wmap/WMapStruct258.java
Refactored some of the stuff around WmapAtmosphericEffectInstance60 and WmapStruct258 to only build the weather effect sprites once at allocation instead of for each instance, which applies to both snow and clouds. Also combined the deallocators, removed some more statics, and refactored a few translation attributes.
Closes #762
> Implemented WMAP snow

- src/main/java/legend/game/Scus94491BpeSegment_8005.java
- src/main/java/legend/game/wmap/MapState100.java
- src/main/java/legend/game/wmap/WMap.java
- src/main/java/legend/game/wmap/WMapStruct258.java
- src/main/java/legend/game/wmap/WmapStatics.java
More names, more enums, more switch refactors. Removed what should be some redundant checks from certain condition chains.
Fixed several things that were messing up the teleportation animations. Now works properly at 60fps with floats.
It's *nearly* the same as retail now minus the screen distortion effect, but I'm just going to wait for that to be implementable to do a final comparison and see if anything actually needs fixing, or if it's the lack of distortion making it seem different.
Closes #887
> More renaming and teleportation fix

- src/main/java/legend/core/gpu/Gpu.java
Fixes crash when game speed multiplier set to 0.
Closes #902
> Re-added game speed multiplier contraints

- src/main/java/legend/game/wmap/WMap.java
- src/main/java/legend/game/wmap/WMapAtmosphericEffectInstance60.java
Speed of UV cycling was to fast, snowflakes weren't bright enough, and snowflakes weren't scaling. This should fix all of those.
Closes #910
> Fixes WMAP snow animation

- src/main/java/legend/game/Scus94491BpeSegment_8002.java
The transfer x/y weren't being cast to int, so their positions weren't in line with the bounds of the scissor.
> Fixed text getting clipped

- src/main/java/legend/game/debugger/CombatDebugger.java
- src/main/java/legend/game/debugger/Debugger.java
- src/main/java/legend/game/debugger/GameStateEditor.java
- src/main/java/legend/game/debugger/GameStateViewer.java
- src/main/java/legend/game/debugger/ScriptDebugger.java
- src/main/java/legend/game/debugger/SmapDebugger.java
- src/main/resources/legend/game/debugger/gamestate_editor.fxml
- src/main/resources/legend/game/debugger/gamestate_viewer.fxml
- Reduce need to drag and manage debugger windows around
- Updated some of the prefHeights and prefWidths to match the layouts
**Motivation**
- Testing the game and wasting too much time moving windows
> Make debugger spawn child windows centered to itself

- src/main/java/legend/game/wmap/WMap.java
Fixes crash reported in discord when running into big dot after leaving hellena the first time. Seems like it enters a branch I didn't realize it would when hitting a terminal dot with no location attached.
> Added null check for wmap prompt deallocation (closes #1191)

- src/main/java/legend/game/combat/ui/BattleHud.java
Changed Z-positioning of actionDisabled so it no longer appears behind combat menu icons
> fixed disabled battle icon order (closes #1414)

- src/main/java/legend/game/inventory/screens/ShopScreen.java
on Shop Screen:
Changed clunky language from "Number kept" to "Carrying"
Changed positioning of text so that it's not all crowded together.
Closes #1500
> Updated language and repositioned text and numbers on Shop Screen Closes #1500

- src/main/java/legend/core/Config.java
- src/main/java/legend/game/Scus94491BpeSegment.java
- src/main/java/legend/game/debugger/DebuggerController.java
Needing to turn the game speed multiplier back to 1 (off) and then back to some higher game speed multipler. And then doing this a thousand times when testing.
I made it so that the extra Config parameter is sourced from config.conf (on load) or Debugger (on set). The +/- shortcuts were intentionally ignored to give a new degree of freedom. Aka, use +/- to customize your session but use the toggle to revert to your preferred config state.
Control + Q.
Not sure what system keys are reserved for. Control+Q is easily accessible (one-handed shortcuts btw) and not in use elsewhere.
There's a lot more that can be done with game speed multipliers. At the moment, it is all tied to the gameSpeedMulitplier static variable in Config. This value should probably be managed in a class that can then …
> Input Toggle for GameSpeedMultiplier

- src/main/java/legend/game/combat/ui/BattleHud.java
- src/main/java/legend/game/combat/ui/BattleMenuStruct58.java
- Playing at high game speed multipliers makes navigating the Battle menu difficult
- Supports accessibility
- Makes one-handed playing easier
- Permits controller + keyboard usages for accessibility (rebinds)
- The game inputs are live but their inputs are unmapped to any actions
- Since the its using the integrated InputAction system, we can scope these to only combat contexts
- Will be seamless with any future hotkey/input rebind functionality later
- Sounds are played on invalid selection w/ a validation check on the hotkey
- Also a utility method within BattleHud that could replace a few dozen playSound lines (refactoring some logic however)
- battleMenu_800c6c34
- Added 2 utility methods to retrieve icon status (todo: remove all the duplicated original utils checking for these icon …
> Combat Hot Keys

- .gitignore
- .idea/.gitignore
- isos/.gitignore
I don't like to cherry-pick files while creating a commit. Ideally you want to ignore any file that is the result from compilation or setup.
> git: Ignore jdk and isos folders

- src/main/java/legend/game/submap/SubmapObject210.java
Integer.MIN_VALUE is 0x8000_0000, which is read as negative 2 billion whatever dec. When tick - Integer.MIN_VALUE is computed, it does not underflow, it just resolves to 0x8000_0001, which is still a negative number, meaning the conditions in scriptSetModelRotate evaluate false instead of true. Expanding the field to a long means the equation evaluates to a positive number instead, as intended. Boat rotation and Giganto arrows also still orient correctly.
Fixes #1641
> Fixed Man in Hood's rotation being wrong

- src/main/java/legend/game/Scus94491BpeSegment_8002.java
Reverted 5e93da73. Textbox position off by less than 8 it was shifted by, caused by float math differences in the calculation of sobj position.
Closes #1673
> Fixed combat text being shifted down

- src/main/java/legend/game/wmap/WMap.java
Wake appeared stair-stepped because the integer angle values lacked the precision necessary for smooth curves at 60fps. Converted remaining math to floats.
Also removed depthOffset render option and moved z offset to transforms. Still unclear why we thought we couldn't do this originally.
> Fixed Queen Fury wake again again probably for real this time

- src/main/java/legend/game/combat/SEffe.java
- src/main/java/legend/game/combat/particles/ParticleEffectData98.java
Caused stupid-big acceleration values in particles that used the acceleration scaler.
Closes #1812 and certainly some others that will need to be looked for.
> Converted acceleration scaler from fip8 to float

- src/main/java/legend/core/RenderEngine.java
- src/main/java/legend/core/opengl/GuiManager.java
- src/main/java/legend/core/opengl/Window.java
- src/main/java/legend/game/input/Input.java
- src/main/java/legend/game/inventory/screens/ControlHost.java
- src/main/java/legend/game/inventory/screens/MenuScreen.java
- src/main/java/legend/game/modding/coremod/CoreMod.java
- src/main/java/legend/game/modding/coremod/config/DisableMouseInputConfigEntry.java
- src/main/java/legend/game/title/Ttle.java
Play Severed Chains with mouse input disabled. 
- Hides mouse cursor
- Disables mouse clicks
- Controls do not react to mouse movement, scrolling, or mouse clicks
- Only works if a controller is connected and in use
- Cursor becomes functional if controller is disconnected
- 💠 Cinematic immersion 💠 
- Controller-only mode (TV setups)
- Avoids niche issues with touchscreen inputs on laptops / TVs / monitors
- In fullscreen border / maximized view the cursor can be hidden
- Great for single monitor users
- Helpful for streaming software compatibility
- Click-through overlay programs will work properly
- Accessibility programs using click-through overlays
- Various mouse based input emulations will work more easily
- ex: emulating a steering wheel on your mouse as your daily driver
- In the …
> Controls Menu | Disable Mouse Input

- src/main/java/legend/game/scripting/GameVarParam.java
Some scripts use the current tick count as a trigger for certain events, usually checking to see if it is an odd number or if it's divisible by a certain amount.
In the case of roaming Hellena Prison wardens in the towers, it checks to see if the current tick count is divisible by 100 or 200 (depending on the tower). The 2x tick multiplier used for 60fps means that they will spawn twice as fast. It also means that if an odd number of ticks are skipped, they'll stop spawning altogether.
closes #1850
> Get retail tick count for submap scripts

- patches/scripts.csv
- patches/scripts/DRGN0/5316/1.diff
One of the oldest remaining bugs, vanquished at last.
Turns out that fixing the crash with #329 didn't break anything, but did reveal that this deff script was already broken. Instead of having the storage for the secondary bobj index that is used to attach parent script translation to the effect initialized properly, in retail it was only working because the manager script happened to be reallocated to the same memory as the previous iteration of itself and accidentally inherited the correct values. Properly setting all storage values to -1 as was done previously is the correct fix for the crash in #174, the deff for the attack needed to be altered to correctly update these storage values before attempting to calculate relative positions.
Fixes #1808
> Fixed Selebus' zambo hand positioning

- src/main/java/legend/game/modding/events/battle/BattleMusicEvent.java
- src/main/java/legend/game/modding/events/submap/SubmapEncounterAccumulatorEvent.java
- src/main/java/legend/game/modding/events/submap/SubmapEncounterRateEvent.java
- src/main/java/legend/game/modding/events/submap/SubmapGenerateEncounterEvent.java
Fix oversight in what mod event properties are moddable and which ones are a) not used after the event, and b) should be for reference only (which is communicated to the modder by the property being 'final' on their end).
If the other properties gain function instead of just context then it is a non-breaking change to un-final them.
> Fix mod events using final on moddable properties

- src/main/java/legend/game/inventory/screens/CharSwapScreen.java
Fixed crash when selecting an empty slot with keyboard/controller.
Fixed mouse click highlight on locked party members.
To account for disabling unlock party with a non-retail party configuration, the party is checked for certain conditions when the character swap screen is loaded. If any of the following are true, the party will be reorganized:
* Swappable character is in a higher slot than a required character
* Slot is empty
* Required character is in the secondary/reserve roster
* First slot is not a required character
~Note:  The only non-retail outcome that can still occur is having required characters in slot 0 and slot 2, with a swappable slot 1.~
_Edit: Locked characters now sort to top. Example of remaining exceptions:
Hellena Prison 2
0 Lavitz
1 Dart
2 Rose_
> Fix Char Swap crash (again) and other input bugs

- patches/scripts.csv
- patches/scripts/DRGN21/249/5.diff
When returning from the rooftop cutscene, Lavitz suggests gathering supplies before leaving Bale. If the player leaves this room and returns, Lavitz's mother will be standing closer to the table, in the position expected for Lavitz's hug cutscene.
This patch adds walking and rotation animations that place her in the correct position after Lavitz suggests ~wasting all of Dart's hard earned gold~ shopping.
[2024-12-26 23-05-54.webm](https://github.com/user-attachments/assets/1bb2d340-4a72-4b41-ad3e-9a022d78114b)
Closes #1196
> Add animation to Lavitz's mother to fix broken hug cutscene

- patches/scripts/DRGN21/249/5.diff
Adds a collision check to walking animation to pause and wait until the player moves away.
Prevents the player from getting stuck if standing too close to her destination.
Patch fix for #1196
> Added collision check to Lavitz Hug patch

- src/main/java/legend/core/RenderEngine.java
We don't need to clear the colour because the framebuffer texture is rendered over the whole screen and is entirely opaque. This means we also don't need to overwrite the current clear colour set by the game.
> Maintain clear colour while paused (closes #1908)

- patches/scripts.csv
- patches/scripts/DRGN22/795/1.diff
Moves the camera above the submap rather than to its left. This places it within the scissor's boundaries to render the scene as expected (still cropped to the submap's width).
Closes #1918
> Adjust camera for Haschel solo punch cutscene

- src/main/java/legend/game/combat/ui/ListMenu.java
- spell_94 is set to null at times and can be null in this flow (item list)
- added an mp check along with proper sounding
The initial values of .spell_94 are likely stale data in some way. Initially thought it was monster entity data being left over in the .spell_94 that was not being set to null on battle load / opening menus after the enemy had taken a turn. But Flameshot and Divine Dragon spells have both appeared as initial stale data for non-Dart characters.
Either nodart is making that more complicated or the spell_94 is being set by a stale/garbage/incorrect index on battle load.
> Fix no MP check on spell list menu

- src/main/java/legend/game/combat/ui/ListMenu.java
- src/main/java/legend/game/combat/ui/SpellListMenu.java
1. The changediff is what clears the stale data and is just there to illustrate the problem
2. Stale data is being populated from enemy turns (aka, garbage data not so much stale data) and is not consistently cleaned up
3. Case 2 needs to be refactored and split each check into a doCase2 for AdditionListMenu, SpellListMenu, and ItemListMenu
4. Likely even the whole tick method and all other cases
- Do you want me to hunt down all leafs in the flow to find where spell_94 and item_d4 should be set to null?
- Refactor just the resetting of these two properties to null before/after/during this Case 2 / onSelection in ListMenu proper?
- Use this fix for now / put in onSelection and reset spell_94 in itemlist and spelllist
- Implement an MP check for ItemListMenu and SpellListMenu (where only …
> discussion listmenu mp fix

- src/main/java/legend/game/combat/particles/PixelParticle.java
> Add missing B+F blending to pixel particles (closes #1810)

- src/main/java/legend/game/combat/ui/BattleHud.java
Forgot to remove early break in blend loop after removing blend loop.
Fixes #1983
> Fix clut for MISS and fix number pop-in

- gfx/shaders/battle_tmd.fsh
- gfx/shaders/tmd.fsh
- src/main/java/legend/core/QueuedModel.java
- src/main/java/legend/core/QueuedModelBattleTmd.java
- src/main/java/legend/core/QueuedModelStandard.java
- src/main/java/legend/core/QueuedModelTmd.java
- src/main/java/legend/core/RenderEngine.java
- src/main/java/legend/core/opengl/MeshObj.java
- src/main/java/legend/core/opengl/Obj.java
- src/main/java/legend/core/opengl/RenderState.java
- src/main/java/legend/core/opengl/TextObj.java
- src/main/java/legend/core/opengl/TmdMeshObj.java
- src/main/java/legend/core/opengl/TmdObjLoader.java
- src/main/java/legend/game/Scus94491BpeSegment_8002.java
- src/main/java/legend/game/submap/SMap.java
(B+F)/2 translucency for TMDs was just broken, used 100% alpha instead of 50%
Added depth culling comparison option to queued models. I had changed it from GL_LESS to GL_LEQUAL a while ago to fix UI rendering, and that actually fixed some other things (like fixing Haschel's face textures not rendering) but also broke other things (chest shadow rendering overtop of open lid). I'm still defauling to GL_LEQUAL, but using GL_LESS for sobj models. No idea if this is breaking/fixing anything else. Turns out retail models are a mess of overlapping geometry.
Overhauled render engine to give it full control over rendering individual layers of models. Before, it worked like this:
1. Render all opaque layers (opaque)
2. Render all translucent layers with translucent texture bit disabled (opaque)
3. …
> Render overhaul part 87

- src/main/java/legend/game/submap/CollisionGeometry.java
- src/main/java/legend/game/submap/SMap.java
- Fixed smoothing so it always applies
- Updated it to run at 60fps
- Tweaked rotation speed slightly
- Increased rotation speed when running by 1.5x to prevent moonwalking
> Fix Dart SMAP rotation (closes #981)

- src/main/java/legend/game/debugger/DebuggerController.java
- src/main/java/legend/game/submap/RetailSubmap.java
- src/main/java/legend/game/submap/SMap.java
- src/main/java/legend/game/submap/Submap.java
- Debugger BattleStage selector did not work for Contact Encounters
- Debugger BattleStage logic was in multiple places
- Encounter flows were divergent and had a mix of duplicated logic in multiple places
- Debugger BattleStageId control works for all encounter types with all stages
- Encounter flow logic consolidated, streamlined, and updated
- Removed 0 being false and an int
- Encounter related mod events will now work for all encounter types
---
**Good**
- Unnest if else logic
- Conform the nested else if to the rest of the method's early return convention
- Make ternary the disjointed logic checks for encounterId_800bb0f8
- Remove unnecessay encounterId blank finalization variable
- 0x1ff -> stageData_80109a98.length as this is what its checking for and what its counterpart does in …
> Improve Encounters

- patches/libs/widescreen.full.txt
- patches/libs/widescreen.txt
- patches/scripts/DRGN21/123/3.diff
- patches/scripts/DRGN21/249/5.diff
- patches/scripts/DRGN21/51/2.diff
- patches/scripts/DRGN21/51/3.diff
- patches/scripts/DRGN21/51/9.diff
- patches/scripts/DRGN21/96/3.diff
- patches/scripts/DRGN22/1137/7.diff
- patches/scripts/DRGN22/1137/8.diff
- patches/scripts/DRGN24/612/3.diff
Updated "widescreen" library for movement with collision waiting.
Updated patch for Lavitz's mom to use new subroutine `DRGN21/249/5.diff`
Fixed bad line metadata on Rose patch `DRGN22/1137/7.diff`
Revised pointer names for Libria patch `DRGN22/1137/8.diff`
Revised patches and commentary for running in place Lavitz `DRGN21/96/3.diff` and Meru `DRGN24/612/3.diff`
Patches with minor updates*:
* Prairie
`DRGN21/123/3.diff`
* Helena Prison - Before first Fruegel fight
`DRGN21/51/2.diff`
`DRGN21/51/3.diff`
`DRGN21/51/9.diff`
*These patches are going to get reapplied due to the library update anyway, so might as well get some improvements and updated commentary in at the same time. Improvements are almost entirely to localizing changes.
> Patch update variety hour

- src/main/java/legend/game/inventory/screens/ShopScreen.java
empty or firstitem is item => useItemShop
elsewise => use equipment stuff for display
Otherwise, crash occurs if the ShopContentEvent clears all inventory and we hit back.
Could solve by using shopType as well but thought not.
> fix shopscreen crash if shop has no inventory on back button action

- src/main/java/legend/game/inventory/screens/CampaignSelectionScreen.java
- On submap load the submapcutforsave does not get set when resuming a campaign from save
- Default value is 0
- New Campaign sets submapcutforsave so no issue there
Fixes debug submap saving in the Crash Recovery save if the crash occurred before mapTransition was called (earliest next call to set submapcutforsave).
> Fix submapcutforsave not being set on campaign select (closes #2054)

- src/main/java/legend/game/EngineState.java
- src/main/java/legend/game/inventory/screens/MainMenuScreen.java
- src/main/java/legend/game/submap/SMap.java
- src/main/java/legend/game/wmap/WMap.java
The Psyche Bomb Trial bug is still a mystery, but this fixes world map loading and switching back to submap music when reloading the current submap.
Closes #2223
Closes #2224
> Fix Load from Main Menu map transitions

- src/main/java/legend/game/Scus94491BpeSegment_8002.java
- src/main/java/legend/game/types/TextboxText84.java
As tick multiplier increases, more lines are skipped. `_3a` reverted back to int. `scrollSpeed_2a` already accounts for the tick multiplier.
Closes #2238
> Fix textbox scrolling

- src/main/java/legend/game/submap/CollisionGeometry.java
- src/main/java/legend/game/submap/SMap.java
Uses Dart's rotation relative to himself rather than relative to the world
> Make collision rotation use local movement (closes #2153)
