build.gradle, src/main/java/legend/game/WMap.java, src/test/java/legend/game/ExampleTest.java
This PR adds JUnit to the project and configs gradle so that it can be run via gradle clean test.  It closes the issue: [Look into setting up a unit testing framework #14](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/issues/14)
I suggest to squash the commits before merging.
=> Setup a unit testing framework (closes #14)

.github/workflows/publish.yml
Github action to build latest JAR.
=> Github build action

.github/workflows/publish.yml
=> Windows build fix for Github Actions

src/main/java/legend/core/Config.java, src/main/java/legend/game/SMap.java, src/main/java/legend/game/Scus94491BpeSegment_8002.java, src/main/java/legend/game/combat/Bttl_800e.java, src/main/java/legend/game/debugger/CombatDebuggerController.java, src/main/java/legend/game/debugger/DebuggerController.java, src/main/resources/legend/game/debugger/combat_debugger.fxml, src/main/resources/legend/game/debugger/debugger.fxml
auto advance text, fast text speed, "auto" charm potion, fix combat debugger not displaying full HP stat
=> additional debugger features

src/main/java/legend/game/WMap.java
Encounters still triggered on the World Map previously. This corrects that from the original PR #272.
=> Added Auto Charm Potion effect to World Map

src/main/java/legend/game/SItem.java
• Floating point division is now respected
• Order of operations is now correct
Closes #141
=> Fixed MP and HP Multipliers not working

README.md, src/main/java/legend/game/input/ControllerDatabase.java, src/main/java/legend/game/input/Input.java, src/main/java/legend/game/input/InputControllerAssigner.java, src/main/java/legend/game/input/InputControllerData.java, src/main/java/legend/game/input/InputMapping.java
- Corrected wrong formatting (used a %d instead of a %s) 
- If any issues with the controllers are detected it now properly goes to Keyboard-Mouse only mode
- In keyboard-mouse only mode it now doesn't attempt to look up mappings in the controller database
- Added a try block on disconnect until the source of the error can be found. Still can't reproduce it locally however normal DS4 controllers do seem to work fine.
- Minor Refactor
- Updated Readme with new controls / controller procedure
=> Input System Tweaks

src/main/java/legend/game/combat/Bttl_800f.java, src/main/java/legend/game/combat/types/BattleObject27c.java
We were packing and unpacking in a way that didn't preserve the sign or value of negative amounts. I chose the solution that involved changing the least amount of code to reduce the risk of missing something.
=> Fix Power Down

src/main/java/legend/game/combat/Bttl_800c.java, src/main/java/legend/game/combat/types/WeaponTrailEffect3c.java
Just a couple things I found looking for the possible weapon trail issues, plus some light renaming. Shouldn't actually change how anything works, so I'm PRing main instead of rc.
=> Fixed some non-bug causing code issues

src/main/java/legend/game/combat/Bttl_800c.java, src/main/java/legend/game/combat/Bttl_800f.java, src/main/java/legend/game/scripting/GameVarArrayParam.java
Typo was writing array values to wrong address.
=> Fixes switching camera views in combat

src/main/java/legend/game/SMap.java, src/main/java/legend/game/Scus94491BpeSegment.java, src/main/java/legend/game/Scus94491BpeSegment_8004.java
Some methods that I identified when I was trying to solve the boat hanging in Bale. Actual bug still a mystery.
=> Renamed some script functions

src/main/java/legend/game/combat/SEffe.java
See LAB_80109b90 in ghidra.
In applyVertexDifferenceAnimation, previous was being set equal to current instead of previous + current.
=> Tiny hands

src/main/java/legend/game/Scus94491BpeSegment_8004.java, src/main/java/legend/game/combat/Bttl_800c.java, src/main/java/legend/game/unpacker/Unpacker.java
Patches DRGN0/5546 with added script code to give Dart back his arm and remove Lavitz's damaged chest plate from behind Albert's head. Unpack required to test.
=> Fixes additional oof visual bugs

src/main/java/legend/game/combat/Bttl_800d.java, src/main/java/legend/game/combat/environment/BattleCamera.java
Fixes some unknown number of camera issues, including Urobolus cutscene, archer attacks, and Rainbow Breath.
Fixes #31 (at least substantially) and #246
=> Camera refpoint fix

src/main/java/legend/core/gpu/Gpu.java, src/main/java/legend/game/SItem.java, src/main/java/legend/game/SMap.java, src/main/java/legend/game/Scus94491BpeSegment.java, src/main/java/legend/game/Scus94491BpeSegment_8002.java, src/main/java/legend/game/Scus94491BpeSegment_8003.java, src/main/java/legend/game/Scus94491BpeSegment_8004.java, src/main/java/legend/game/Scus94491BpeSegment_800e.java, src/main/java/legend/game/WMap.java, src/main/java/legend/game/combat/Bttl_800c.java, src/main/java/legend/game/fmv/Fmv.java, src/main/java/legend/game/title/Ttle.java
Also makes it so display height can be adjusted
=> Restore menu widths to original truncated size (closes #472)

src/main/java/legend/game/Scus94491BpeSegment.java
=> Fixes logging for script <

src/main/java/legend/game/combat/Bttl_800e.java, src/main/java/legend/game/combat/bobj/BattleObject27c.java, src/main/java/legend/game/combat/types/MonsterStats1c.java
Figure out while stepping through enemy script to create counter table.
=> Named field _7e based on counter research

log4j2.xml, src/main/java/legend/game/combat/Bttl_800d.java
Just in case we need it at some point. Turned off by default.
=> Camera logging

src/main/java/legend/core/Config.java, src/main/java/legend/core/gpu/Gpu.java, src/main/java/legend/game/Scus94491BpeSegment_8002.java, src/main/java/legend/game/debugger/DebuggerController.java, src/main/java/legend/game/types/Translucency.java, src/main/resources/legend/game/debugger/debugger.fxml
Moved around a few things in the debug window and made it bigger. Added RGB options for the text box.  There is new transparency modes as well added for the change.
=> RGB Text Boxes and Debugger Window Reorg

src/main/java/legend/game/combat/Bttl_800c.java, src/main/java/legend/game/combat/SEffe.java
Fixed 3 separate issues in the logic branch of the electricity rendering code for Doel's lighning bomb. May fix other electricity effects somewhere else.
=> Fixed Doel's lightning bomb and ???

src/main/java/legend/game/combat/SEffe.java
Only red channel was being shifted in renderer. Fixes Spear Frost, at least one Meru effect, and ???
=> Fix ice chunk red color

src/main/java/legend/game/Scus94491BpeSegment.java, src/main/java/legend/game/Scus94491BpeSegment_800b.java, src/main/java/legend/game/WMap.java, src/main/java/legend/game/combat/Bttl_800c.java, src/main/java/legend/game/title/Ttle.java, src/main/java/legend/game/types/McqHeader.java, src/main/java/legend/game/unpacker/FileData.java
We weren't able to reproduce the issue, but this'll make it impossible
=> Dememulate MCQs (closes #593)

src/main/java/legend/game/input/Input.java
=> Fix input continuing when window out of focus

src/main/java/legend/game/combat/SEffe.java, src/main/java/legend/game/combat/effects/ElectricityEffect38.java, src/main/java/legend/game/combat/effects/LightningBoltEffect14.java, src/main/java/legend/game/combat/effects/LightningBoltEffectSegment30.java, src/main/java/legend/game/combat/effects/LightningBoltEffectSegmentOrigin08.java
Effects seem to be working correctly.
=> Electric dememulation

src/main/java/legend/game/combat/Bttl_800d.java, src/main/java/legend/game/combat/effects/AdditionStarburstEffect10.java, src/main/java/legend/game/combat/effects/AdditionStarburstEffectRay10.java
=> Fully dememulated starburst

src/main/java/legend/game/combat/Bttl_800c.java, src/main/java/legend/game/combat/effects/WeaponTrailEffect3c.java, src/main/java/legend/game/combat/effects/WeaponTrailEffectSegment2c.java
Kanzas didn't explode in testing, so it should be working.
=> Finished dememulating weapon trail effect

src/main/java/legend/game/combat/Bttl_800c.java, src/main/java/legend/game/combat/Bttl_800d.java, src/main/java/legend/game/combat/effects/AdditionStarburstEffect10.java, src/main/java/legend/game/combat/effects/AdditionStarburstEffectRay10.java
Converted ray effect to ref struct and refactored
=> Starburst dememulation

src/main/java/legend/game/combat/SEffe.java, src/main/java/legend/game/combat/effects/LensFlareEffect50.java
Named last field and converted a couple globals to array refs.
=> Additional lens flare changes

src/main/java/legend/game/Scus94491BpeSegment_8004.java, src/main/java/legend/game/combat/SEffe.java, src/main/java/legend/game/combat/effects/WsDragoonTransformationFeatherInstance70.java, src/main/java/legend/game/combat/effects/WsDragoonTransformationFeathersEffect14.java
Not actually sure what fixed it, but somewhere during the dememulation process the feather contraction started working properly.
=> Dememulated and fixed feather effect for WS Dragoon transformation

src/main/java/legend/game/Scus94491BpeSegment.java, src/main/java/legend/game/Scus94491BpeSegment_8004.java
Fixes some effects and models being flipped upsidedown
=> Do math properly (closes #671)

src/main/java/legend/game/SMap.java, src/main/java/legend/game/Scus94491BpeSegment_8003.java, src/main/java/legend/game/Scus94491BpeSegment_800c.java, src/main/java/legend/game/combat/Bttl_800d.java, src/main/java/legend/game/title/Ttle.java
- Switched all cameras to use the higher precision method
- Yote bithacking
=> Refactor camera math code

src/main/java/legend/game/combat/Bttl_800d.java, src/main/java/legend/game/combat/environment/BattleCamera.java
=> More naming

src/main/java/legend/game/SMap.java, src/main/java/legend/game/combat/Bttl_800e.java, src/main/java/legend/game/combat/environment/BttlLightStruct84Sub38.java
Fixes the lighting over-saturation in submaps and combat.
=> Lighting fix

src/main/java/legend/game/Scus94491BpeSegment_8003.java, src/main/java/legend/game/submap/SMap.java
Added a copy of GsSetRefView2L just for SMAP to do int math on the values prior to converting them to normalized floats.
=> Embaddened Smap camera math

src/main/java/legend/game/wmap/WMap.java
=> Fixed location menu ordering and added rendering for barrier station options

src/main/java/legend/core/GameEngine.java, src/main/java/legend/core/RenderEngine.java, src/main/java/legend/core/opengl/MeshObj.java, src/main/java/legend/core/opengl/Obj.java, src/main/java/legend/core/opengl/QuadBuilder.java, src/main/java/legend/core/opengl/TextBuilder.java, src/main/java/legend/core/opengl/TextObj.java, src/main/java/legend/core/opengl/TmdObjLoader.java, src/main/java/legend/game/Scus94491BpeSegment.java, src/main/java/legend/game/Scus94491BpeSegment_8002.java, src/main/java/legend/game/combat/Bttl_800c.java, src/main/java/legend/game/combat/Bttl_800d.java, src/main/java/legend/game/submap/SMap.java, src/main/java/legend/game/wmap/WMap.java, src/main/java/legend/game/wmap/WmapPromptPopup.java
This doesn't feel right, but it sure makes it easy to find the issue.
Closes #788
=> Tracking for Objs

src/main/java/legend/game/Scus94491BpeSegment_8002.java
=> Fixed textbox arrow brightness

src/main/java/legend/game/wmap/CoolonQueenFuryOverlay.java, src/main/java/legend/game/wmap/WMap.java
The square button with the little icon in the bottom right.
Closes #792
=> Enter Coolon/Queen Fury overlay

src/main/java/legend/game/wmap/WMap.java, src/main/java/legend/game/wmap/WmapPromptPopup.java
Fixed ordering of location prompt boxes, tweaked positioning
=> Fixed ordering of location prompt boxes, tweaked positioning

src/main/java/legend/game/Scus94491BpeSegment_8004.java, src/main/java/legend/game/wmap/ColourBlending20.java, src/main/java/legend/game/wmap/WMap.java, src/main/java/legend/game/wmap/WMapStruct258.java, src/main/java/legend/game/wmap/WMapTextHighlightSubRectVertexColours10.java, src/main/java/legend/game/wmap/WmapMenuTextHighlight40.java, src/main/java/legend/game/wmap/WmapPromptPopup.java
-Implemented the prompt for Coolon travel
-Refactored shadow/selector text highlights into WmapPromptPopup to yeet statics and bundle the prompt elements
-Converted some int colors to floats
-Fixed some new math bugs regarding prompt shadow brightness
=> Coolon move prompt

src/main/java/legend/game/Scus94491BpeSegment_8002.java, src/main/java/legend/game/wmap/WMap.java
Start labels, zoomed out destination label, Coolon destination label
Also fixed text shadow ordering and merged the loops in renderTextboxes.
Closes #768
=> Wmap place labels

src/main/java/legend/game/combat/Bttl_800c.java, src/main/java/legend/game/submap/SMap.java, src/main/java/legend/game/wmap/WMap.java
=> Used deleteModelParts for other Model124 instances

src/main/java/legend/game/wmap/WMap.java, src/main/java/legend/game/wmap/WMapAtmosphericEffectInstance60.java, src/main/java/legend/game/wmap/WMapStruct258.java
=> Implemented WMAP clouds in opengl

src/main/java/legend/game/wmap/WMap.java
The translation tick for snowflakes did not get adjusted for 60fps and was moving too fast.
=> Fixed WMAP snow movement for 60fps

src/main/java/legend/game/wmap/MapMarker.java, src/main/java/legend/game/wmap/WMap.java, src/main/java/legend/game/wmap/WMapAtmosphericEffectInstance60.java, src/main/java/legend/game/wmap/WMapStruct258.java
In addition to implementing the markers in opengl, I also renamed a few more things and fixed a few issues that had snuck by with the wmap labels.
Closes #775 
Creates #866, but want to handle that later.
=> Implemented WMAP markers

src/main/java/legend/game/wmap/WMap.java
=> Fixes WMAP water z-fighting

src/main/java/legend/game/wmap/WmapMenuTextHighlight40.java, src/main/java/legend/game/wmap/WmapPromptPopup.java
=> Fixed prompt highlights rebuilding every tick

src/main/java/legend/game/submap/SMap.java
=> Copy-paste oopsie

src/main/java/legend/game/submap/SMap.java
=> Fixed SMAP model obj leak

src/main/java/legend/game/submap/ChapterTitleCard.java, src/main/java/legend/game/submap/SMap.java
Refactored title card stuff into own class and converted to opengl.
Closes #961
=> Implement chapter title cards in opengl

src/main/java/legend/core/RenderEngine.java
F9 - advance one frame
F10 - advance frames while held
=> Added frame advance

src/main/java/legend/game/Scus94491BpeSegment_8002.java
=> Adjusted text arrow for 60fps

src/main/java/legend/core/RenderEngine.java, src/main/java/legend/game/fmv/Fmv.java
=> Fixes FMV positioning, final FMV crash, and FMVs not being visible

src/main/java/legend/game/submap/RetailSubmap.java
=> Fixes end cut not loading

src/main/java/legend/game/combat/bent/PlayerBattleEntity.java
fixes ultimate wargod, wargod's calling, destroyer mace not working
=> Fix Player Equipment getStat (closes #1209)

src/main/java/legend/game/combat/ui/BattleHud.java
Draw lines and SP bars updated to OpenGL.
=> Draw Lines and SP Bars Closes #817

src/main/java/legend/game/submap/SMap.java
12 hours of digging to change a single parameter
=> pass submap scene on chapter change (closes #1009)

gfx/shaders/tmd.fsh, gfx/shaders/tmd.vsh, src/main/java/legend/game/SItem.java, src/main/java/legend/game/combat/Battle.java, src/main/java/legend/game/combat/SEffe.java, src/main/java/legend/game/combat/bent/BattleEntity27c.java, src/main/java/legend/game/submap/RetailSubmap.java, src/main/java/legend/game/submap/SMap.java
closes #1238
closes #1069
closes #1064
closes #1050
closes #1028
closes #881
=> Possibly fix all depth issues

src/main/java/legend/game/submap/SMap.java
not sure if this fixes anything else
=> make scripts read screen offset destination (closes #1100)

src/main/java/legend/game/submap/SMap.java
=> rounding on dart's position on submap load

src/main/java/legend/game/combat/Battle.java
=> add missing annotation to script method

src/main/java/legend/game/inventory/screens/PostBattleScreen.java
Partial revert of Pull Request https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/pull/1509/files
=> fix: xp gain issue

src/main/java/legend/game/combat/Battle.java, src/main/java/legend/game/combat/SEffe.java, src/main/java/legend/game/combat/effects/ModelEffect13c.java, src/main/java/legend/game/types/Model124.java
dobj coords were not getting copied over to cloned models.
=> Fixed T-pose in certain animations

patches/scripts/throw_item.txt
=> Backs up throw sprite index for status items

patches/scripts.csv, patches/scripts/DRGN23/12/1.diff
=> Fixed messed up retail text in Furni (closes #1484)

src/main/java/legend/game/Scus94491BpeSegment_8003.java, src/main/java/legend/game/Scus94491BpeSegment_800c.java, src/main/java/legend/game/combat/SEffe.java, src/main/java/legend/game/combat/effects/DeffTmdRenderer14.java, src/main/java/legend/game/combat/particles/TmdParticle.java
Closes #1377, #1313, #1562 for sure, testing needed for others. Had to account for cancel out w2s transformation for use in opengl.
=> Fixed TMD particle and some DEFF TMD transformation issues

src/main/java/legend/core/RenderEngine.java, src/main/java/legend/game/combat/SEffe.java, src/main/java/legend/game/combat/effects/RainEffect08.java
Java modulo strikes again.
Also added adjustment for raindrop count based on screen width. Would like other opinions on if it seems like a similar density, or if the counts were already overestimated and just rendering off-screen before merging.
Fixes #1807
=> Fixed sparse rain effect

src/main/java/legend/core/QueuedModel.java, src/main/java/legend/core/RenderBatch.java, src/main/java/legend/core/RenderEngine.java, src/main/java/legend/core/gpu/Rect4i.java, src/main/java/legend/core/opengl/RenderState.java, src/main/java/legend/core/opengl/ScissorStack.java, src/main/java/legend/game/submap/RetailSubmap.java, src/main/java/legend/game/submap/SMap.java, src/main/java/legend/game/submap/Submap.java
=> Add hierarchical scissoring and prevent rendering past the edges of a submap when in extended mode (closes #1816)

src/main/java/legend/game/combat/SEffe.java, src/main/java/legend/game/combat/effects/WsDragoonTransformationFeatherInstance70.java, src/main/java/legend/game/combat/effects/WsDragoonTransformationFeathersEffect14.java
A couple of angles had been converted to floats, but everything else was still in int/fip8.
Fixes #1819
=> Fixed feather movement in Shana's Dragoon transformation

src/main/java/legend/game/submap/SMap.java
Encounters were starting sooner by factor of 16
=> Encounter rate fix

src/main/java/legend/game/combat/effects/LmbAnimationEffect5c.java
=> Missed including poly stuff in LMB type 1

src/main/java/legend/core/QueuedModel.java, src/main/java/legend/game/Scus94491BpeSegment.java, src/main/java/legend/game/Scus94491BpeSegment_8002.java, src/main/java/legend/game/combat/Battle.java, src/main/java/legend/game/combat/SEffe.java, src/main/java/legend/game/combat/bent/BattleEntity27c.java, src/main/java/legend/game/combat/effects/DeffTmdRenderer14.java, src/main/java/legend/game/combat/effects/GenericSpriteEffect24.java, src/main/java/legend/game/combat/effects/LmbAnimationEffect5c.java, src/main/java/legend/game/combat/effects/ModelEffect13c.java, src/main/java/legend/game/combat/effects/ShadowEffect.java, src/main/java/legend/game/combat/effects/SpriteWithTrailEffect30.java, src/main/java/legend/game/submap/AttachedSobjEffect.java, src/main/java/legend/game/submap/RetailSubmap.java, src/main/java/legend/game/submap/SMap.java
=> Removed zOffset static usage from opengl rendering

src/main/java/legend/game/combat/SEffe.java, src/main/java/legend/game/combat/effects/LensFlareEffect50.java, src/main/java/legend/game/combat/effects/LensFlareEffectInstance3c.java
Melbu transition flare now working after #1865 
Closes #1858
=> Implemented lens flare effect in opengl

src/main/java/legend/game/combat/SEffe.java, src/main/java/legend/game/combat/effects/GoldDragoonTransformEffect20.java, src/main/java/legend/game/combat/effects/GoldDragoonTransformEffectInstance84.java
=> Implemented Golden Dragoon Transformation rocks in opengl

src/main/java/legend/game/combat/effects/StarChildrenImpactEffect20.java
=> Implemented Star Children explosions in opengl

src/main/java/legend/game/combat/SEffe.java, src/main/java/legend/game/combat/effects/GoldDragoonTransformEffect20.java
I will change it if you make me, but I won't be happy about it.
=> Only load Golden Dragoon rock TMD once

src/main/java/legend/game/combat/Battle.java, src/main/java/legend/game/combat/SEffe.java, src/main/java/legend/game/combat/bent/BattleEntity27c.java, src/main/java/legend/game/combat/effects/DeffTmdRenderer14.java, src/main/java/legend/game/combat/effects/GenericSpriteEffect24.java, src/main/java/legend/game/combat/effects/LmbAnimationEffect5c.java, src/main/java/legend/game/combat/effects/ModelEffect13c.java, src/main/java/legend/game/submap/RetailSubmap.java, src/main/java/legend/game/submap/SMap.java
=> Fixed zShift missing from depths after #1865

src/main/java/legend/game/wmap/WMap.java
=> Needed to add a monochrome call to shadow after #1859 changes

src/main/java/legend/game/inventory/screens/CharSwapScreen.java
=> Fix unlock party mouse click

patches/scripts.csv, patches/scripts/DRGN22/1098/1.diff
=> Fix Dart cutscene animation in Princess Emille's room

patches/scripts/DRGN22/798/1.config.csv, patches/scripts/DRGN22/798/1.diff
=> Fix crash related to broken table in patch

src/main/resources/lod_core/lang/en.lang
=> Add en.lang entry for Disable Mouse Input config

patches/scripts.csv, patches/scripts/DRGN22/672/7.diff, patches/scripts/DRGN22/672/8.diff
=> Fix Twin Castle evening guard flashing

patches/scripts/DRGN22/807/1.config.csv
=> Broken table DRGN22/807/1

patches/scripts/DRGN22/807/1.config.csv, patches/scripts/DRGN22/807/1.diff
=> Regen patch for broken table DRGN22/807/1

patches/scripts/DRGN22/807/1.config.csv, patches/scripts/DRGN22/807/1.diff
Regenerated patch
Related to #1772 and #1920
=> Broken tables DRGN22/807/1

src/main/java/legend/game/input/Input.java, src/main/java/legend/game/inventory/screens/KeybindsScreen.java, src/main/resources/lod_core/lang/en.lang
=> feat: GLFW mods support

src/main/java/legend/core/Config.java, src/main/java/legend/core/RenderEngine.java, src/main/java/legend/game/input/Input.java, src/main/java/legend/game/input/InputAction.java, src/main/java/legend/game/modding/coremod/CoreMod.java, src/main/resources/lod_core/lang/en.lang
=> feat: full screen keybind

src/main/java/legend/game/combat/effects/GradientRaysEffect24.java
=> Imago gradient rays fix

src/main/java/legend/game/Scus94491BpeSegment_8002.java
=> Fix colons rendering on some menus (closes #1948)

src/main/java/legend/game/combat/effects/GenericSpriteEffect24.java
=> Fixes Gravity Grabber circle and Death Dim glow

src/main/java/legend/game/fmv/Fmv.java, src/main/resources/lod_core/lang/en.lang
=> feat: cutscene skips on double tap

src/main/java/legend/game/combat/ui/BattleHud.java
Also switched the grayscale base CLUT to the version with the mbit enabled.
Fixes #837
=> Re-add translucency check and switch to alpha transparency

src/main/java/legend/core/audio/AudioSource.java, src/main/java/legend/core/audio/AudioThread.java
=> fix audiodevice change crash (closes #1734)

src/main/java/legend/game/submap/SMap.java
=> Restored positive index check to SMap::scriptGetCollisionPrimitivePos

src/main/java/legend/game/inventory/screens/ControlHost.java, src/main/java/legend/game/inventory/screens/OptionsScreen.java, src/main/resources/lod_core/lang/en.lang
=> Error handling on OptionsScreen to handle errors thrown by configs

src/main/java/legend/game/modding/events/submap/SubmapWarpEvent.java, src/main/java/legend/game/submap/SMap.java
=> Submap warp event closes #2066

src/main/java/legend/game/submap/RetailSubmap.java, src/main/java/legend/game/submap/SMap.java
Closes #1311 
Closes #1792 
Closes #1835
=> Fix submap layering issues (closes #1311, closes #1835)

src/main/java/legend/game/inventory/screens/AdditionsScreen.java, src/main/java/legend/game/inventory/screens/CharSwapScreen.java, src/main/java/legend/game/inventory/screens/ControlHost.java, src/main/java/legend/game/inventory/screens/EquipmentScreen.java, src/main/java/legend/game/inventory/screens/GoodsScreen.java, src/main/java/legend/game/inventory/screens/ItemListScreen.java, src/main/java/legend/game/inventory/screens/MainMenuScreen.java, src/main/java/legend/game/inventory/screens/MessageBoxScreen.java, src/main/java/legend/game/inventory/screens/OptionsScreen.java, src/main/java/legend/game/inventory/screens/ShopScreen.java, src/main/java/legend/game/inventory/screens/StatusScreen.java, src/main/java/legend/game/inventory/screens/TooManyItemsScreen.java, src/main/java/legend/game/inventory/screens/TooltipScreen.java, src/main/java/legend/game/inventory/screens/UseItemScreen.java, src/main/java/legend/game/inventory/screens/VerticalLayoutScreen.java, src/main/java/legend/game/inventory/screens/controls/BigList.java, src/main/java/legend/game/inventory/screens/controls/Checkbox.java, src/main/java/legend/game/inventory/screens/controls/Dropdown.java, src/main/java/legend/game/inventory/screens/controls/ItemList.java, src/main/java/legend/game/inventory/screens/controls/ListBox.java, src/main/java/legend/game/inventory/screens/controls/NumberSpinner.java
Add list wrapping
Fix input sounds
Fix compatible character filtering in shop menus
Closes #296
Closes #1754
Closes #2112
=> Polish multiple menus

src/main/java/legend/game/sound/Sequencer.java
=> Fix portamento octave bug

patches/scripts.csv, patches/scripts/DRGN24/918/10.diff, patches/scripts/DRGN24/918/3.diff, patches/scripts/DRGN24/918/4.diff, patches/scripts/DRGN24/918/5.diff, patches/scripts/DRGN24/918/6.diff
=> Fix Kraken cutscene

src/main/java/legend/game/inventory/screens/ShopScreen.java
=> Fix equipment buy price when not equipping

patches/scripts/DRGN22/804/1.diff
=> Fix double Haschel in Gehrich cutscene

src/main/java/legend/game/inventory/screens/UseItemScreen.java
=> Fix crash when using last remaining item

patches/scripts/DRGN22/669/6.diff, patches/scripts/DRGN22/669/7.diff, patches/scripts/DRGN22/681/1.diff
=> More Twin Castle widescreen patches

src/main/java/legend/game/inventory/screens/ShopScreen.java
=> Fix crash when selling last item or equip

src/main/java/legend/game/Scus94491BpeSegment_8002.java, src/main/java/legend/game/inventory/screens/MainMenuScreen.java, src/main/java/legend/game/modding/coremod/CoreMod.java, src/main/java/legend/game/modding/coremod/config/AutoTextDelayConfigEntry.java, src/main/resources/lod_core/lang/en.lang
Auto-text advance delay default is 1 second.
Closes #2207.
Closes #2209.
Closes #2212.
=> Add auto-text advance delay option, add Load to main menu, save anywhere toggle fix

src/main/java/legend/game/inventory/screens/ShopScreen.java
=> Fix enter/space crash on shop buy with full inventory and portrait refresh on sell

src/main/java/legend/game/inventory/screens/ShopScreen.java
=> Fix shop crash using keyboard to buy item/equip without enough gold

patches/scripts/DRGN22/1104/1.diff
Closes #2268. Related to #2027
=> Fix textbox position for Emille painting widescreen patch

patches/scripts.csv, patches/scripts/DRGN21/426/1.diff, patches/scripts/DRGN21/426/7.diff, patches/scripts/DRGN21/687/6.diff
=> Widescreen patches for Lohan and Black Castle

src/main/java/legend/game/combat/bent/MonsterBattleEntity.java
Edited the Z depth of the HP bar UI elements to be behind other UI elements.
=> Fixes #1496 HP Bar Depth

patches/scripts/DRGN0/5520/1.diff, patches/scripts/DRGN0/5532/1.diff
=> Remove leading space on diff comment lines

src/main/java/legend/game/inventory/screens/MainMenuScreen.java, src/main/java/legend/game/submap/SMap.java, src/main/java/legend/game/wmap/WMap.java
Got some fields to name later, _800bd7ac, _800bd7b0
=> Fix loading from menu

src/main/java/discord/DiscordRichPresence.java
Oh well theres a typo in commit message but whatever
=> Unbreak game (no dicord installed) (closes #2342)
